swagger: "2.0"
info:
  version: 1.0.0
  title: Actividad final 1
  description: Aplicación Almacén
tags:
  - name: recursos
    description: Archivo configuración aplicación almacén 
schemes:
  - http
paths:
  /posts:
    get:
      description: Devuelve todos los articulos del almacén
      tags:
      - recursos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: Consulta de la lista del recurso.
        "400":
          description: Error
    post:
      description: Añade un producto nuevo a los artículos del almacén
      responses:
        "201":
          description: OK. La creación del articulo ha ido bien
          tags:
          - recursos
          content:
            application/json:
              schema:
                type: string
                description: Se crea un nuevo producto en la lista de articulos.
        "400":
          description: Error
          requestBody:
            application/json:
              schema:
                type: string
                description: No se ha creado el producto
  /posts/{id}:
    get:
      description: Consulta de articulo en concreto de los que hay en el almacén
      tags:
      - recursos
      responses:
        "200":
          description: OK. Devuelve el post consultado
          content:
            application/json:
              schema:
                type: string
                description: Consulta de un articulo
        "400":
          description: Error. No se ha encontrado el articulo requerido
    delete:
      description: Borra un actículo concreto de la lista de articulos
      tags:
      - recursos
      responses:
        "204":
          description: Artículo borrado
        "404":
          description: No se ha podido borrar el artículo
    put:
      description: Se utiliza para actualizar un producto de la lista de artículos
      parameters:
        - name: userId
          schema:
            type: string
      requestBody:
        description: Actualiza un articulo existente en el almacén
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userId'
      responses:
        default:
          description: Operación exitosa




          
basedatos:
  path: {{path y fichero de la base de datos}}
  consumidor_almacen: {{nombre del consumidor}}
  consumidor_almacen_key: {{valor API KEY para invocar al api para el con consumidor anterior}}  